Repository boxy-smd/deck-web, pull requests merged in 2024-09, with the labels that each got.

#10 feature/create-publish-project-flow
  biome.json
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/app/profile/[profileid]/page.tsx
  src/app/project/[projectid]/edit/page.tsx
  src/app/project/[projectid]/page.tsx
  src/components/create-project-form.tsx
  src/components/ui/bubble-button.tsx
  src/components/ui/button.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/command.tsx
  src/components/ui/dialog.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/editor.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/link-button.tsx
  src/components/ui/menubar-combobox.tsx
  src/components/ui/menubar.tsx
  src/components/ui/popover.tsx
  src/components/ui/select.tsx
  src/components/ui/textarea.tsx
  src/components/ui/toggle-group.tsx
  src/components/ui/toggle.tsx
  src/lib/tiptap.ts
  tailwind.config.ts
Labels: feature

#15 feature: slash command
  package.json
  pnpm-lock.yaml
  src/app/project/[projectid]/edit/page.tsx
  src/components/create-project-form.tsx
  src/components/project-card-preview.tsx
  src/components/project-card.tsx
  src/components/ui/button.tsx
  src/components/ui/command.tsx
  src/components/ui/editor.tsx
  src/components/ui/link-button.tsx
  src/components/ui/menubar-combobox.tsx
  src/components/ui/menubar.tsx
  src/components/ui/popover.tsx
  src/components/ui/select.tsx
  src/components/ui/textarea.tsx
  src/components/ui/toggle.tsx
  tsconfig.json
Labels: feature

#17 feat: create profile page
  package-lock.json
  src/app/(base)/profile/[profileId]/page.tsx
  src/components/profile/modal-profile.tsx
  src/components/profile/profile-card.tsx
Labels: feature

#18 fix: update profile page
  src/app/(base)/profile/[profileId]/page.tsx
Labels: fix

#19 fix: update filter popover
  package-lock.json
  src/app/(base)/page.tsx
  src/app/(base)/profile/[profileId]/page.tsx
  src/components/filter/filter-projects.tsx
Labels: fix

#21 refactor: button back project view
  src/app/project/[projectid]/page.tsx
  src/components/ui/button.tsx
Labels: refactor

#28 docs: update readme
  README.md
Labels: documentation

#29 feat: add query libs
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/components/base/header.tsx
  src/components/filter/search-input-with-filters.tsx
  src/entities/comment.ts
  src/entities/professor.ts
  src/entities/profile.ts
  src/entities/project.ts
  src/entities/subject.ts
  src/entities/trail.ts
  src/lib/axios.ts
  src/lib/tanstack-query/client.ts
  src/lib/tanstack-query/query-provider.tsx
Labels: feature

#30 feat: connect authentication flow to api
  src/app/(auth)/login/page.tsx
  src/app/(auth)/register/page.tsx
  src/app/layout.tsx
  src/components/base/header.tsx
  src/components/base/profile-image.tsx
  src/components/register/register-mail-step.tsx
  src/components/register/register-more-you-step.tsx
  src/components/register/register-name-step.tsx
  src/components/ui/dropdown-menu.tsx
  src/contexts/hooks/use-logged-student.ts
  src/contexts/logged-student-context.tsx
  src/hooks/auth/use-login.ts
  src/hooks/auth/use-register.ts
  src/lib/axios.ts
Labels: feature

#32 feat: connect profile page to api
  src/app/(base)/page.tsx
  src/app/(base)/profile/[profileId]/page.tsx
  src/app/(base)/profile/[username]/page.tsx
  src/app/(base)/search/page.tsx
  src/components/base/header.tsx
  src/components/profile/modal-profile.tsx
  src/components/profile/profile-card.tsx
  src/components/project-card.tsx
  src/components/ui/badge.tsx
  src/contexts/logged-student-context.tsx
  src/entities/profile.ts
  src/entities/project.ts
  src/hooks/auth/use-login.ts
Labels: feature

#33 feat: integrate create project backend
  .env
  .env.example
  .gitignore
  package.json
  pnpm-lock.yaml
  src/app/(base)/page.tsx
  src/app/(base)/profile/[username]/page.tsx
  src/app/(base)/search/page.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/layout.tsx
  src/app/project/[projectid]/edit/page.tsx
  src/app/project/[projectid]/page.tsx
  src/app/project/publish/page.tsx
  src/components/base/header.tsx
  src/components/create-project-form.tsx
  src/components/profile/profile-card.tsx
  src/components/project-card-preview.tsx
  src/components/project-card.tsx
  src/components/project-view.tsx
  src/components/publish/content-preview.tsx
  src/components/publish/sidebar.tsx
  src/components/publish/steps/document-project.tsx
  src/components/publish/steps/preview-project.tsx
  src/components/publish/steps/register-project.tsx
  src/components/register/register-more-you-step.tsx
  src/components/register/register-name-step.tsx
  src/components/ui/command.tsx
  src/components/ui/dialog.tsx
  src/components/ui/menubar-combobox.tsx
  src/components/ui/menubar.tsx
  src/components/ui/select.tsx
  src/components/ui/skeleton.tsx
  src/components/ui/switch.tsx
  src/components/ui/tabs.tsx
  src/components/ui/toggle.tsx
  src/contexts/hooks/use-logged-student.ts
  src/contexts/logged-student-context.tsx
  src/entities/profile.ts
  src/entities/project.ts
  src/hooks/auth/use-login.ts
  src/hooks/auth/use-register.ts
  src/lib/axios.ts
  src/lib/tiptap.ts
  src/providers/session-provider.tsx
  src/styles/globals.css
  src/types/next-auth.d.ts
Labels: feature

#34 feat: create edit profile flow
  src/app/project/publish/page.tsx
  src/components/filter/search-input-with-filters.tsx
  src/components/profile/modal-profile.tsx
  src/components/profile/profile-card.tsx
  src/components/register/register-more-you-step.tsx
  src/components/ui/command.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/hover-card.tsx
  src/components/ui/popover.tsx
  src/components/ui/select.tsx
Labels: feature

#35 refactor: create custom hooks and contexts
  src/app/(auth)/login/page.tsx
  src/app/(base)/page.tsx
  src/app/(base)/profile/[username]/page.tsx
  src/app/(base)/search/page.tsx
  src/app/layout.tsx
  src/app/project/publish/layout.tsx
  src/app/project/publish/page.tsx
  src/components/base/header.tsx
  src/components/filter/filter-projects.tsx
  src/components/filter/search-input-with-filters.tsx
  src/components/profile/modal-profile.tsx
  src/components/profile/profile-card.tsx
  src/components/project-view.tsx
  src/components/publish/steps/register-project.tsx
  src/components/register/register-more-you-step.tsx
  src/components/student-card.tsx
  src/contexts/authenticated-student-context.tsx
  src/contexts/hooks/use-authenticated-student.ts
  src/contexts/hooks/use-tags-dependencies.ts
  src/contexts/tags-context.tsx
  src/entities/profile.ts
  src/functions/drafts.ts
  src/functions/projects.ts
  src/functions/students.ts
  src/hooks/auth/use-register.ts
  src/hooks/project/use-publish-project.ts
  src/lib/tiptap.ts
Labels: refactor

#37 feat: start implement high fidelity
  src/app/(auth)/login/page.tsx
  src/components/ui/button.tsx
  src/components/ui/input.tsx
  tailwind.config.ts
Labels: feature

#39 feat: start implement high fidelity
  src/app/(auth)/login/page.tsx
  src/components/ui/button.tsx
  src/components/ui/input.tsx
  tailwind.config.ts
Labels: feature

#40 feat: create portfolio page
  package.json
  pnpm-lock.yaml
  public/next.svg
  public/vercel.svg
  src/app/(base)/portfolio/[username]/page.tsx
  src/components/portfolio/document.tsx
  src/components/profile/profile-card.tsx
  src/entities/profile.ts
Labels: feature

#43 fix: adjust bugs
  src/components/assets/audiovisual.tsx
  src/components/assets/design.tsx
  src/components/assets/games.tsx
  src/components/assets/smd.tsx
  src/components/assets/systems.tsx
  src/components/profile/modal-profile.tsx
  src/components/profile/profile-card.tsx
  src/functions/projects.ts
  src/functions/students.ts
  src/hooks/auth/use-register.ts
  src/hooks/project/use-publish-project.ts
Labels: fix

#45 fix: update components
  src/app/project/[projectid]/page.tsx
  src/components/project-view.tsx
Labels: fix

#46 Layout for high fidelity
  src/app/(base)/profile/[username]/page.tsx
  src/app/project/[projectid]/page.tsx
  src/components/project-view.tsx
Labels: feature

#47 Feat add widget
  src/app/(auth)/login/page.tsx
  src/app/(auth)/register/page.tsx
  src/app/(base)/page.tsx
  src/app/(base)/profile/[username]/page.tsx
  src/app/(base)/search/page.tsx
  src/assets/widgets/authWidgets/authWidget.svg
  src/assets/widgets/authWidgets/finishRegisterWidget.svg
  src/assets/widgets/authWidgets/loginWidget.svg
  src/assets/widgets/authWidgets/registerWidget.svg
  src/assets/widgets/homeWidget.svg
  src/assets/widgets/projectPostWidget.svg
  src/assets/widgets/searchWidget.svg
  src/components/register/register-mail-step.tsx
  src/components/register/register-more-you-step.tsx
Labels: feature

#49 feat: adjust components and add metadata
  src/app/(auth)/login/page.tsx
  src/app/(auth)/register/page.tsx
  src/app/(base)/profile/[username]/page.tsx
  src/app/favicon.ico
  src/app/icon.svg
  src/app/layout.tsx
  src/app/project/publish/page.tsx
  src/assets/Logo.svg
  src/components/filter/filter-projects.tsx
  src/components/profile/modal-profile.tsx
  src/components/profile/profile-card.tsx
  src/components/project-card.tsx
  src/components/project-view.tsx
  src/components/publish/content-preview.tsx
  src/components/publish/steps/preview-project.tsx
  src/components/publish/steps/register-project.tsx
  src/components/register/register-mail-step.tsx
  src/components/register/register-more-you-step.tsx
  src/components/ui/select.tsx
  src/components/ui/tabs.tsx
  src/components/ui/toggle.tsx
  src/entities/project.ts
  src/functions/projects.ts
  src/functions/students.ts
  src/hooks/auth/use-login.ts
  src/hooks/auth/use-register.ts
  src/hooks/project/use-publish-project.ts
Labels: feature, refactor, fix

#50 fix: layout with no filter found
  src/app/(base)/page.tsx
Labels: fix
